language: cpp

# We depend on revision numbering here
git:
  depth: false

# We release every commit, which creates tags, avoid building twice
if: tag IS blank

matrix:
  include:
  - os: linux
    name: "Script build"
    dist: xenial
    script:
      - BUILD=$(($(git rev-list --count --first-parent HEAD)+3500))
      - echo "Build number ${BUILD}"
      - mkdir -p ciout
      - LAST=$(<current/last)
      - if [ "$LAST" == "" ]; then LAST=1; fi
      - if [ -f current/last_en ]; then LAST_EN=$(<current/last_en); else LAST_EN="$LAST" ; fi
      - if [ -f current/last_cn ]; then LAST_CN=$(<current/last_cn); else LAST_CN="$LAST" ; fi
      - if [ -f current/last_ru ]; then LAST_RU=$(<current/last_ru); else LAST_RU="$LAST" ; fi
      - if [ -f current/last_pt ]; then LAST_PT=$(<current/last_pt); else LAST_PT="$LAST" ; fi
      - php update-manager/update-manager.php dscript "ciout/en.txt" . en ${BUILD} || exit 1
      - php update-manager/update-manager.php dscript "ciout/ru.txt" . ru ${BUILD} || exit 1
      - php update-manager/update-manager.php dscript "ciout/pt.txt" . pt ${BUILD} || exit 1
      - php update-manager/update-manager.php dscript "ciout/cn.txt" . cn ${BUILD} || exit 1
      - php update-manager/update-manager.php dscript "ciout/wh.txt" . wh ${BUILD} || exit 1
      - cp misc/chiru.file ciout
      - cp misc/game.hash ciout
      - cp misc/default.cfg ciout
      - cp misc/pt.cfg ciout
      - cp misc/cn.cfg ciout
      - cd ciout
      - zip -qry umineko-main-scripts_r${BUILD}_dev.zip ru.txt en.txt chiru.file game.hash default.cfg || exit 1
      - zip -qry umineko-pt-scripts_r${BUILD}_dev.zip pt.txt pt.cfg || exit 1
      - zip -qry umineko-cn-scripts_r${BUILD}_dev.zip cn.txt cn.cfg || exit 1
      - zip -qry umineko-wh-scripts_r${BUILD}_dev.zip wh.txt || exit 1
      - cd ..
      - php update-manager/update-manager.php script ciout/en.txt "ciout/en.file" "$LAST_EN" || exit 1
      - php update-manager/update-manager.php script ciout/ru.txt "ciout/ru.file" "$LAST_RU" || exit 1
      - php update-manager/update-manager.php script ciout/pt.txt "ciout/pt.file" "$LAST_PT" || exit 1
      - php update-manager/update-manager.php script ciout/cn.txt "ciout/cn.file" "$LAST_CN" || exit 1
      - php update-manager/update-manager.php script ciout/wh.txt "ciout/wh.file" "$LAST_EN" || exit 1
      - cd ciout
      - zip -qry umineko-main-scripts_r${BUILD}.zip ru.file en.file chiru.file game.hash default.cfg || exit 1
      - zip -qry umineko-pt-scripts_r${BUILD}.zip pt.file pt.cfg || exit 1
      - zip -qry umineko-cn-scripts_r${BUILD}.zip cn.file cn.cfg || exit 1
      - zip -qry umineko-wh-scripts_r${BUILD}.zip wh.file || exit 1
      - cd ..

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: avahdduoEOdHSgri7WKP9owmj0Kaf9sJ5fHGaAAMpijqUtOo5pi0Uw4LK2BRLVKa+5bojZfSJN3rmtQkxIsE8MXKl+AKnrqbIzkgZs65vWR7tL/X3/VPef0O/ujwQAgjCXcYgCc/MFz2CsfZb4PAnBDu9wo2THkoqQH5GSat/gj1xgD+Ig9+BxzL5ykUr1zd4PoJVtF85zzYyxOLm6n1v1lWBtqhP95/AYNbwv9tobCXZ6HGCCEhV57xX2r01U31Bi9kIcR5gtiVJIPCw5LaRfeSLX1pD52rIzSpfzrAl/yv9dl6LUUVN0BR/BALjBWkUyg1t7PKlM7cDui78dlZh21eDfbnYpq1pPVKn4p2lyylXYVm/niePTIZHuCaCXOA2YkyrzXqg2FiFfeBMwxO9PhEjd65UInx6gPjuHLW00BUODDYW37S/L3Mo2O7lPVM4d2hg7UlpmtEqk6lHePFlM+jLUOjod20GhibnN4W28oZ5wvziWIUtSLKu3cQWJ59ROYTRDfabH/zMm/g1hNUaTxZRaC9woDNVyTltE/UIINAQjRcsHGjPwWmuMShMPCSCHCWD/9EbRnOC4HDOGLguI+02u3yOeg6HH5+6vmPqA+WwnDbJg9z/w/n4sXJpoUu/fOkKSLW++THHEpG1bWyBQGuJpFwkCFE6qEkUW5Ytig=
  file_glob: true
  file: ciout/*.zip
  name: "Umineko Scripts r${BUILD}"
  on:
    tags: false
    repo: umineko-project/umineko-scripting
    branch: master
